"""
Real University and Program Seed Data
Data sourced from QS World University Rankings 2024, THE Rankings 2024, and official university websites.
Last verified: January 2026

IMPORTANT: This data is the source of truth for AI recommendations.
AI must NEVER generate or modify university facts.
"""
from datetime import datetime

VERIFIED_AT = datetime(2026, 1, 31)
DATA_SOURCE = "QS 2024, THE 2024, Official Websites (Jan 2026)"

# ~75 Real Universities with verified program data
UNIVERSITIES_DATA = [
    # ============================================
    # USA - Top Universities (~30)
    # ============================================
    {
        "name": "Massachusetts Institute of Technology",
        "country": "USA",
        "city": "Cambridge, MA",
        "qs_ranking": 1,
        "the_ranking": 3,
        "official_website": "https://www.mit.edu",
        "is_public": False,
        "description": "World's leading university in science, engineering, and technology",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "EECS",
                "duration_months": 24,
                "tuition_per_year_usd": 58240,
                "min_gpa": 3.5,
                "ielts_min": 7.0,
                "toefl_min": 100,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI/ML", "Systems", "Theory", "HCI"],
            },
            {
                "name": "MS Data Science",
                "degree_level": "Masters",
                "department": "IDSS",
                "duration_months": 12,
                "tuition_per_year_usd": 58240,
                "min_gpa": 3.5,
                "ielts_min": 7.0,
                "toefl_min": 100,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 15",
                "specializations": ["Statistics", "Machine Learning"],
            },
        ],
    },
    {
        "name": "Stanford University",
        "country": "USA",
        "city": "Stanford, CA",
        "qs_ranking": 5,
        "the_ranking": 2,
        "official_website": "https://www.stanford.edu",
        "is_public": False,
        "description": "Leading university in innovation, entrepreneurship, and technology",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "School of Engineering",
                "duration_months": 21,
                "tuition_per_year_usd": 57861,
                "min_gpa": 3.6,
                "ielts_min": 7.0,
                "toefl_min": 100,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 1",
                "specializations": ["AI", "Systems", "Theory", "HCI"],
            },
        ],
    },
    {
        "name": "Carnegie Mellon University",
        "country": "USA",
        "city": "Pittsburgh, PA",
        "qs_ranking": 52,
        "the_ranking": 24,
        "official_website": "https://www.cmu.edu",
        "is_public": False,
        "description": "Top-ranked computer science and engineering programs globally",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "School of Computer Science",
                "duration_months": 16,
                "tuition_per_year_usd": 52816,
                "min_gpa": 3.5,
                "ielts_min": 7.5,
                "toefl_min": 100,
                "gre_required": True,
                "gre_min": 320,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 13",
                "specializations": ["AI/ML", "Robotics", "Systems", "Security"],
            },
            {
                "name": "MS Machine Learning",
                "degree_level": "Masters",
                "department": "School of Computer Science",
                "duration_months": 24,
                "tuition_per_year_usd": 52816,
                "min_gpa": 3.5,
                "ielts_min": 7.5,
                "toefl_min": 100,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 13",
                "specializations": ["Deep Learning", "NLP", "CV"],
            },
        ],
    },
    {
        "name": "University of California, Berkeley",
        "country": "USA",
        "city": "Berkeley, CA",
        "qs_ranking": 10,
        "the_ranking": 9,
        "official_website": "https://www.berkeley.edu",
        "is_public": True,
        "description": "Premier public research university with strong STEM programs",
        "programs": [
            {
                "name": "MS EECS",
                "degree_level": "Masters",
                "department": "EECS",
                "duration_months": 24,
                "tuition_per_year_usd": 28176,
                "min_gpa": 3.5,
                "ielts_min": 7.0,
                "toefl_min": 90,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 8",
                "specializations": ["AI", "Systems", "Theory"],
            },
        ],
    },
    {
        "name": "Georgia Institute of Technology",
        "country": "USA",
        "city": "Atlanta, GA",
        "qs_ranking": 88,
        "the_ranking": 33,
        "official_website": "https://www.gatech.edu",
        "is_public": True,
        "description": "Top public technical university with affordable tuition",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "College of Computing",
                "duration_months": 24,
                "tuition_per_year_usd": 18024,
                "min_gpa": 3.3,
                "ielts_min": 7.0,
                "toefl_min": 90,
                "gre_required": True,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "February 1",
                "specializations": ["ML", "Systems", "HCI", "Graphics"],
            },
            {
                "name": "MS Data Science & Analytics",
                "degree_level": "Masters",
                "department": "College of Computing",
                "duration_months": 18,
                "tuition_per_year_usd": 18024,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 85,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "March 1",
                "specializations": ["Analytics", "Business"],
            },
        ],
    },
    {
        "name": "University of Illinois Urbana-Champaign",
        "country": "USA",
        "city": "Urbana, IL",
        "qs_ranking": 64,
        "the_ranking": 48,
        "official_website": "https://illinois.edu",
        "is_public": True,
        "description": "Strong engineering and computer science tradition",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "CS Department",
                "duration_months": 20,
                "tuition_per_year_usd": 38568,
                "min_gpa": 3.2,
                "ielts_min": 6.5,
                "toefl_min": 96,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI", "Systems", "Data"],
            },
        ],
    },
    {
        "name": "University of Michigan",
        "country": "USA",
        "city": "Ann Arbor, MI",
        "qs_ranking": 33,
        "the_ranking": 23,
        "official_website": "https://umich.edu",
        "is_public": True,
        "description": "Top public university with excellent engineering school",
        "programs": [
            {
                "name": "MS Computer Science & Engineering",
                "degree_level": "Masters",
                "department": "CSE",
                "duration_months": 20,
                "tuition_per_year_usd": 28512,
                "min_gpa": 3.3,
                "ielts_min": 6.5,
                "toefl_min": 84,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "January 15",
                "specializations": ["AI", "Systems", "Theory"],
            },
        ],
    },
    {
        "name": "University of Texas at Austin",
        "country": "USA",
        "city": "Austin, TX",
        "qs_ranking": 58,
        "the_ranking": 47,
        "official_website": "https://www.utexas.edu",
        "is_public": True,
        "description": "Major research university in tech hub Austin",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "CS Department",
                "duration_months": 24,
                "tuition_per_year_usd": 20912,
                "min_gpa": 3.2,
                "ielts_min": 6.5,
                "toefl_min": 79,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI", "Systems", "Graphics"],
            },
        ],
    },
    {
        "name": "Purdue University",
        "country": "USA",
        "city": "West Lafayette, IN",
        "qs_ranking": 99,
        "the_ranking": 86,
        "official_website": "https://www.purdue.edu",
        "is_public": True,
        "description": "Strong STEM university known for engineering excellence",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "CS Department",
                "duration_months": 24,
                "tuition_per_year_usd": 31104,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 80,
                "gre_required": True,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "December 15",
                "specializations": ["Systems", "Security", "ML"],
            },
        ],
    },
    {
        "name": "University of Washington",
        "country": "USA",
        "city": "Seattle, WA",
        "qs_ranking": 63,
        "the_ranking": 26,
        "official_website": "https://www.washington.edu",
        "is_public": True,
        "description": "Top CS program in tech hub Seattle",
        "programs": [
            {
                "name": "MS Computer Science & Engineering",
                "degree_level": "Masters",
                "department": "Paul G. Allen School",
                "duration_months": 18,
                "tuition_per_year_usd": 38796,
                "min_gpa": 3.3,
                "ielts_min": 7.0,
                "toefl_min": 92,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI", "Systems", "HCI"],
            },
        ],
    },
    {
        "name": "University of California, San Diego",
        "country": "USA",
        "city": "San Diego, CA",
        "qs_ranking": 62,
        "the_ranking": 32,
        "official_website": "https://ucsd.edu",
        "is_public": True,
        "description": "Strong research university with excellent CS department",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "CSE",
                "duration_months": 24,
                "tuition_per_year_usd": 26544,
                "min_gpa": 3.2,
                "ielts_min": 7.0,
                "toefl_min": 85,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI", "Systems", "Bioinformatics"],
            },
        ],
    },
    {
        "name": "University of Southern California",
        "country": "USA",
        "city": "Los Angeles, CA",
        "qs_ranking": 116,
        "the_ranking": 65,
        "official_website": "https://www.usc.edu",
        "is_public": False,
        "description": "Major private university with strong industry connections",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "Viterbi School",
                "duration_months": 20,
                "tuition_per_year_usd": 45378,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 90,
                "gre_required": True,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI", "Games", "Data Science"],
            },
        ],
    },
    {
        "name": "New York University",
        "country": "USA",
        "city": "New York, NY",
        "qs_ranking": 38,
        "the_ranking": 27,
        "official_website": "https://www.nyu.edu",
        "is_public": False,
        "description": "Urban university strong in data science and AI",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "Courant Institute",
                "duration_months": 24,
                "tuition_per_year_usd": 51828,
                "min_gpa": 3.3,
                "ielts_min": 7.0,
                "toefl_min": 100,
                "gre_required": True,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "December 12",
                "specializations": ["AI", "Theory", "Graphics"],
            },
            {
                "name": "MS Data Science",
                "degree_level": "Masters",
                "department": "Center for Data Science",
                "duration_months": 24,
                "tuition_per_year_usd": 51828,
                "min_gpa": 3.3,
                "ielts_min": 7.0,
                "toefl_min": 100,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 12",
                "specializations": ["ML", "NLP", "Statistics"],
            },
        ],
    },
    {
        "name": "Columbia University",
        "country": "USA",
        "city": "New York, NY",
        "qs_ranking": 23,
        "the_ranking": 17,
        "official_website": "https://www.columbia.edu",
        "is_public": False,
        "description": "Ivy League university with strong engineering and data science",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "CS Department",
                "duration_months": 18,
                "tuition_per_year_usd": 58728,
                "min_gpa": 3.4,
                "ielts_min": 7.0,
                "toefl_min": 101,
                "gre_required": True,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "December 15",
                "specializations": ["ML", "NLP", "Vision", "Systems"],
            },
        ],
    },
    {
        "name": "University of Pennsylvania",
        "country": "USA",
        "city": "Philadelphia, PA",
        "qs_ranking": 12,
        "the_ranking": 13,
        "official_website": "https://www.upenn.edu",
        "is_public": False,
        "description": "Ivy League with strong interdisciplinary programs",
        "programs": [
            {
                "name": "MS Computer & Information Science",
                "degree_level": "Masters",
                "department": "CIS",
                "duration_months": 20,
                "tuition_per_year_usd": 53166,
                "min_gpa": 3.3,
                "ielts_min": 7.5,
                "toefl_min": 100,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI", "Robotics", "Theory"],
            },
        ],
    },
    {
        "name": "Cornell University",
        "country": "USA",
        "city": "Ithaca, NY",
        "qs_ranking": 13,
        "the_ranking": 20,
        "official_website": "https://www.cornell.edu",
        "is_public": False,
        "description": "Ivy League with strong CS and engineering programs",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "CIS",
                "duration_months": 20,
                "tuition_per_year_usd": 34380,
                "min_gpa": 3.4,
                "ielts_min": 7.0,
                "toefl_min": 100,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 1",
                "specializations": ["AI", "Systems", "Graphics"],
            },
        ],
    },
    {
        "name": "Northeastern University",
        "country": "USA",
        "city": "Boston, MA",
        "qs_ranking": 375,
        "the_ranking": 168,
        "official_website": "https://www.northeastern.edu",
        "is_public": False,
        "description": "Known for co-op programs and industry partnerships",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "Khoury College",
                "duration_months": 20,
                "tuition_per_year_usd": 29720,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "April 15",
                "specializations": ["AI", "Data", "Systems"],
            },
            {
                "name": "MS Data Science",
                "degree_level": "Masters",
                "department": "Khoury College",
                "duration_months": 20,
                "tuition_per_year_usd": 29720,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "April 15",
                "specializations": ["ML", "Analytics"],
            },
        ],
    },
    {
        "name": "Arizona State University",
        "country": "USA",
        "city": "Tempe, AZ",
        "qs_ranking": 179,
        "the_ranking": 105,
        "official_website": "https://www.asu.edu",
        "is_public": True,
        "description": "Large public research university known for innovation",
        "programs": [
            {
                "name": "MS Computer Science",
                "degree_level": "Masters",
                "department": "SCAI",
                "duration_months": 24,
                "tuition_per_year_usd": 19152,
                "min_gpa": 3.0,
                "ielts_min": 6.0,
                "toefl_min": 80,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "June 1",
                "specializations": ["AI", "Big Data", "Cybersecurity"],
            },
        ],
    },
    # ============================================
    # UK Universities (~15)
    # ============================================
    {
        "name": "University of Oxford",
        "country": "UK",
        "city": "Oxford",
        "qs_ranking": 3,
        "the_ranking": 1,
        "official_website": "https://www.ox.ac.uk",
        "is_public": True,
        "description": "World's oldest English-speaking university",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "CS Department",
                "duration_months": 12,
                "tuition_per_year_usd": 41560,
                "min_gpa": 3.7,
                "ielts_min": 7.5,
                "toefl_min": 110,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "January 20",
                "specializations": ["AI", "Theory", "Verification"],
            },
        ],
    },
    {
        "name": "University of Cambridge",
        "country": "UK",
        "city": "Cambridge",
        "qs_ranking": 2,
        "the_ranking": 5,
        "official_website": "https://www.cam.ac.uk",
        "is_public": True,
        "description": "World-class research university with rich history",
        "programs": [
            {
                "name": "MPhil Advanced Computer Science",
                "degree_level": "Masters",
                "department": "Computer Laboratory",
                "duration_months": 12,
                "tuition_per_year_usd": 40250,
                "min_gpa": 3.7,
                "ielts_min": 7.5,
                "toefl_min": 110,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 3",
                "specializations": ["AI", "Systems", "Security"],
            },
        ],
    },
    {
        "name": "Imperial College London",
        "country": "UK",
        "city": "London",
        "qs_ranking": 6,
        "the_ranking": 8,
        "official_website": "https://www.imperial.ac.uk",
        "is_public": True,
        "description": "Leading STEM-focused university in London",
        "programs": [
            {
                "name": "MSc Computing",
                "degree_level": "Masters",
                "department": "DoC",
                "duration_months": 12,
                "tuition_per_year_usd": 42150,
                "min_gpa": 3.5,
                "ielts_min": 7.0,
                "toefl_min": 100,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "Rolling",
                "specializations": ["AI/ML", "Visual Computing", "Security"],
            },
            {
                "name": "MSc Machine Learning",
                "degree_level": "Masters",
                "department": "DoC",
                "duration_months": 12,
                "tuition_per_year_usd": 42150,
                "min_gpa": 3.5,
                "ielts_min": 7.0,
                "toefl_min": 100,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "Rolling",
                "specializations": ["Deep Learning", "NLP", "CV"],
            },
        ],
    },
    {
        "name": "University College London",
        "country": "UK",
        "city": "London",
        "qs_ranking": 9,
        "the_ranking": 22,
        "official_website": "https://www.ucl.ac.uk",
        "is_public": True,
        "description": "London's leading multidisciplinary university",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "CS",
                "duration_months": 12,
                "tuition_per_year_usd": 37350,
                "min_gpa": 3.3,
                "ielts_min": 7.0,
                "toefl_min": 92,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "March 31",
                "specializations": ["AI", "HCI", "Security"],
            },
            {
                "name": "MSc Data Science",
                "degree_level": "Masters",
                "department": "CS",
                "duration_months": 12,
                "tuition_per_year_usd": 37350,
                "min_gpa": 3.3,
                "ielts_min": 7.0,
                "toefl_min": 92,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "March 31",
                "specializations": ["ML", "Statistics"],
            },
        ],
    },
    {
        "name": "University of Edinburgh",
        "country": "UK",
        "city": "Edinburgh",
        "qs_ranking": 22,
        "the_ranking": 30,
        "official_website": "https://www.ed.ac.uk",
        "is_public": True,
        "description": "Scotland's leading university with strong AI research",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "Informatics",
                "duration_months": 12,
                "tuition_per_year_usd": 32180,
                "min_gpa": 3.3,
                "ielts_min": 7.0,
                "toefl_min": 92,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "Rolling",
                "specializations": ["AI", "ML", "NLP"],
            },
            {
                "name": "MSc Artificial Intelligence",
                "degree_level": "Masters",
                "department": "Informatics",
                "duration_months": 12,
                "tuition_per_year_usd": 32180,
                "min_gpa": 3.3,
                "ielts_min": 7.0,
                "toefl_min": 92,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "Rolling",
                "specializations": ["ML", "Robotics", "NLP"],
            },
        ],
    },
    {
        "name": "University of Manchester",
        "country": "UK",
        "city": "Manchester",
        "qs_ranking": 32,
        "the_ranking": 51,
        "official_website": "https://www.manchester.ac.uk",
        "is_public": True,
        "description": "Major research university with strong industry links",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "CS",
                "duration_months": 12,
                "tuition_per_year_usd": 30850,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 89,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "Rolling",
                "specializations": ["AI", "Data", "Systems"],
            },
        ],
    },
    {
        "name": "King's College London",
        "country": "UK",
        "city": "London",
        "qs_ranking": 40,
        "the_ranking": 38,
        "official_website": "https://www.kcl.ac.uk",
        "is_public": True,
        "description": "Russell Group university in central London",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "Informatics",
                "duration_months": 12,
                "tuition_per_year_usd": 30890,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 87,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "July 26",
                "specializations": ["AI", "Security", "Data Science"],
            },
        ],
    },
    {
        "name": "University of Bristol",
        "country": "UK",
        "city": "Bristol",
        "qs_ranking": 55,
        "the_ranking": 76,
        "official_website": "https://www.bristol.ac.uk",
        "is_public": True,
        "description": "Research-intensive university with excellent CS department",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "CS",
                "duration_months": 12,
                "tuition_per_year_usd": 29450,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 85,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "July 1",
                "specializations": ["AI", "Robotics", "Vision"],
            },
        ],
    },
    {
        "name": "University of Warwick",
        "country": "UK",
        "city": "Coventry",
        "qs_ranking": 67,
        "the_ranking": 104,
        "official_website": "https://warwick.ac.uk",
        "is_public": True,
        "description": "Top modern university with strong industry connections",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "DCS",
                "duration_months": 12,
                "tuition_per_year_usd": 29800,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 87,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "July 31",
                "specializations": ["AI", "Data Science", "Cyber"],
            },
        ],
    },
    {
        "name": "University of Glasgow",
        "country": "UK",
        "city": "Glasgow",
        "qs_ranking": 76,
        "the_ranking": 89,
        "official_website": "https://www.gla.ac.uk",
        "is_public": True,
        "description": "Ancient university with excellent computing research",
        "programs": [
            {
                "name": "MSc Computing Science",
                "degree_level": "Masters",
                "department": "Computing Science",
                "duration_months": 12,
                "tuition_per_year_usd": 26500,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "August 31",
                "specializations": ["AI", "Data Science", "Software"],
            },
        ],
    },
    # ============================================
    # Canada (~10)
    # ============================================
    {
        "name": "University of Toronto",
        "country": "Canada",
        "city": "Toronto, ON",
        "qs_ranking": 21,
        "the_ranking": 21,
        "official_website": "https://www.utoronto.ca",
        "is_public": True,
        "description": "Canada's top research university, leading in AI",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "CS Department",
                "duration_months": 20,
                "tuition_per_year_usd": 21580,
                "min_gpa": 3.3,
                "ielts_min": 7.0,
                "toefl_min": 93,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 1",
                "specializations": ["AI", "ML", "Systems", "Theory"],
            },
        ],
    },
    {
        "name": "University of British Columbia",
        "country": "Canada",
        "city": "Vancouver, BC",
        "qs_ranking": 34,
        "the_ranking": 41,
        "official_website": "https://www.ubc.ca",
        "is_public": True,
        "description": "Pacific Rim research university with strong CS",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "CS Department",
                "duration_months": 24,
                "tuition_per_year_usd": 9102,
                "min_gpa": 3.3,
                "ielts_min": 7.0,
                "toefl_min": 100,
                "gre_required": True,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI", "Graphics", "HCI"],
            },
        ],
    },
    {
        "name": "McGill University",
        "country": "Canada",
        "city": "Montreal, QC",
        "qs_ranking": 30,
        "the_ranking": 49,
        "official_website": "https://www.mcgill.ca",
        "is_public": True,
        "description": "Canada's most international research university",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "SOCS",
                "duration_months": 24,
                "tuition_per_year_usd": 8450,
                "min_gpa": 3.3,
                "ielts_min": 6.5,
                "toefl_min": 86,
                "gre_required": False,
                "intake_terms": ["Fall", "Winter"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI", "Theory", "Systems"],
            },
        ],
    },
    {
        "name": "University of Waterloo",
        "country": "Canada",
        "city": "Waterloo, ON",
        "qs_ranking": 112,
        "the_ranking": 158,
        "official_website": "https://uwaterloo.ca",
        "is_public": True,
        "description": "Canada's tech hub with strongest co-op program",
        "programs": [
            {
                "name": "MMath Computer Science",
                "degree_level": "Masters",
                "department": "David R. Cheriton School",
                "duration_months": 20,
                "tuition_per_year_usd": 7858,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 90,
                "gre_required": False,
                "intake_terms": ["Fall", "Winter", "Spring"],
                "application_deadline_fall": "December 1",
                "specializations": ["AI", "Security", "Systems"],
            },
        ],
    },
    {
        "name": "University of Alberta",
        "country": "Canada",
        "city": "Edmonton, AB",
        "qs_ranking": 111,
        "the_ranking": 109,
        "official_website": "https://www.ualberta.ca",
        "is_public": True,
        "description": "Top AI research center, home of AlphaGo team",
        "programs": [
            {
                "name": "MSc Computing Science",
                "degree_level": "Masters",
                "department": "CS Department",
                "duration_months": 24,
                "tuition_per_year_usd": 6842,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 90,
                "gre_required": False,
                "intake_terms": ["Fall", "Winter"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI/RL", "ML", "Bioinformatics"],
            },
        ],
    },
    {
        "name": "University of Montreal",
        "country": "Canada",
        "city": "Montreal, QC",
        "qs_ranking": 141,
        "the_ranking": 111,
        "official_website": "https://www.umontreal.ca",
        "is_public": True,
        "description": "Home of Mila, world's largest deep learning lab",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "DIRO",
                "duration_months": 24,
                "tuition_per_year_usd": 5500,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 85,
                "gre_required": False,
                "intake_terms": ["Fall", "Winter"],
                "application_deadline_fall": "February 1",
                "specializations": ["Deep Learning", "NLP", "CV"],
            },
        ],
    },
    {
        "name": "Simon Fraser University",
        "country": "Canada",
        "city": "Burnaby, BC",
        "qs_ranking": 318,
        "the_ranking": 201,
        "official_website": "https://www.sfu.ca",
        "is_public": True,
        "description": "Research university with strong tech industry ties",
        "programs": [
            {
                "name": "MSc Computing Science",
                "degree_level": "Masters",
                "department": "CS",
                "duration_months": 24,
                "tuition_per_year_usd": 7200,
                "min_gpa": 3.0,
                "ielts_min": 7.0,
                "toefl_min": 93,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring", "Summer"],
                "application_deadline_fall": "January 31",
                "specializations": ["AI", "Graphics", "HCI"],
            },
        ],
    },
    # ============================================
    # Germany (~10)
    # ============================================
    {
        "name": "Technical University of Munich",
        "country": "Germany",
        "city": "Munich",
        "qs_ranking": 37,
        "the_ranking": 30,
        "official_website": "https://www.tum.de",
        "is_public": True,
        "description": "Germany's top technical university, no tuition fees",
        "programs": [
            {
                "name": "MSc Informatics",
                "degree_level": "Masters",
                "department": "Informatics",
                "duration_months": 24,
                "tuition_per_year_usd": 340,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 88,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "May 31",
                "specializations": ["AI", "Robotics", "Visual Computing"],
            },
            {
                "name": "MSc Data Engineering and Analytics",
                "degree_level": "Masters",
                "department": "Informatics",
                "duration_months": 24,
                "tuition_per_year_usd": 340,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 88,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "May 31",
                "specializations": ["Data Science", "ML", "Big Data"],
            },
        ],
    },
    {
        "name": "RWTH Aachen University",
        "country": "Germany",
        "city": "Aachen",
        "qs_ranking": 92,
        "the_ranking": 90,
        "official_website": "https://www.rwth-aachen.de",
        "is_public": True,
        "description": "Germany's largest technical university",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "Informatik",
                "duration_months": 24,
                "tuition_per_year_usd": 600,
                "min_gpa": 2.7,
                "ielts_min": 6.0,
                "toefl_min": 80,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "March 1",
                "specializations": ["Software", "Media", "Data"],
            },
            {
                "name": "MSc Data Science",
                "degree_level": "Masters",
                "department": "Informatik",
                "duration_months": 24,
                "tuition_per_year_usd": 600,
                "min_gpa": 2.5,
                "ielts_min": 6.0,
                "toefl_min": 80,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "March 1",
                "specializations": ["ML", "Big Data", "Analytics"],
            },
        ],
    },
    {
        "name": "Heidelberg University",
        "country": "Germany",
        "city": "Heidelberg",
        "qs_ranking": 47,
        "the_ranking": 47,
        "official_website": "https://www.uni-heidelberg.de",
        "is_public": True,
        "description": "Germany's oldest university with strong research",
        "programs": [
            {
                "name": "MSc Scientific Computing",
                "degree_level": "Masters",
                "department": "IWR",
                "duration_months": 24,
                "tuition_per_year_usd": 400,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 90,
                "gre_required": False,
                "intake_terms": ["Fall"],
                "application_deadline_fall": "March 15",
                "specializations": ["Simulation", "ML", "Data"],
            },
        ],
    },
    {
        "name": "Karlsruhe Institute of Technology",
        "country": "Germany",
        "city": "Karlsruhe",
        "qs_ranking": 119,
        "the_ranking": 189,
        "official_website": "https://www.kit.edu",
        "is_public": True,
        "description": "Major technical university with strong CS",
        "programs": [
            {
                "name": "MSc Informatics",
                "degree_level": "Masters",
                "department": "Informatik",
                "duration_months": 24,
                "tuition_per_year_usd": 400,
                "min_gpa": 2.7,
                "ielts_min": 6.0,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "March 15",
                "specializations": ["Software", "Theory", "Systems"],
            },
        ],
    },
    {
        "name": "Technical University of Berlin",
        "country": "Germany",
        "city": "Berlin",
        "qs_ranking": 154,
        "the_ranking": 140,
        "official_website": "https://www.tu-berlin.de",
        "is_public": True,
        "description": "Major tech university in Germany's startup capital",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "EECS",
                "duration_months": 24,
                "tuition_per_year_usd": 350,
                "min_gpa": 2.5,
                "ielts_min": 6.0,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "March 15",
                "specializations": ["AI", "Software", "Networks"],
            },
        ],
    },
    {
        "name": "LMU Munich",
        "country": "Germany",
        "city": "Munich",
        "qs_ranking": 54,
        "the_ranking": 38,
        "official_website": "https://www.lmu.de",
        "is_public": True,
        "description": "Bavaria's leading research university",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "Informatik",
                "duration_months": 24,
                "tuition_per_year_usd": 350,
                "min_gpa": 2.7,
                "ielts_min": 6.0,
                "toefl_min": 80,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "July 15",
                "specializations": ["AI", "Bioinformatics", "Media"],
            },
        ],
    },
    {
        "name": "University of Freiburg",
        "country": "Germany",
        "city": "Freiburg",
        "qs_ranking": 192,
        "the_ranking": 108,
        "official_website": "https://uni-freiburg.de",
        "is_public": True,
        "description": "Strong in autonomous systems and AI",
        "programs": [
            {
                "name": "MSc Computer Science",
                "degree_level": "Masters",
                "department": "Informatik",
                "duration_months": 24,
                "tuition_per_year_usd": 400,
                "min_gpa": 2.5,
                "ielts_min": 6.0,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["Fall", "Spring"],
                "application_deadline_fall": "May 15",
                "specializations": ["AI", "Robotics", "ML"],
            },
        ],
    },
    # ============================================
    # Australia (~10)
    # ============================================
    {
        "name": "University of Melbourne",
        "country": "Australia",
        "city": "Melbourne, VIC",
        "qs_ranking": 14,
        "the_ranking": 37,
        "official_website": "https://www.unimelb.edu.au",
        "is_public": True,
        "description": "Australia's leading research university",
        "programs": [
            {
                "name": "Master of Computer Science",
                "degree_level": "Masters",
                "department": "CIS",
                "duration_months": 24,
                "tuition_per_year_usd": 34880,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["March", "July"],
                "application_deadline_fall": "October 31",
                "specializations": ["AI", "Distributed", "HCI"],
            },
            {
                "name": "Master of Data Science",
                "degree_level": "Masters",
                "department": "CIS",
                "duration_months": 24,
                "tuition_per_year_usd": 34880,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["March", "July"],
                "application_deadline_fall": "October 31",
                "specializations": ["ML", "Statistics", "Analytics"],
            },
        ],
    },
    {
        "name": "University of Sydney",
        "country": "Australia",
        "city": "Sydney, NSW",
        "qs_ranking": 19,
        "the_ranking": 60,
        "official_website": "https://www.sydney.edu.au",
        "is_public": True,
        "description": "Australia's first and most prestigious university",
        "programs": [
            {
                "name": "Master of Computer Science",
                "degree_level": "Masters",
                "department": "School of CS",
                "duration_months": 18,
                "tuition_per_year_usd": 36500,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 85,
                "gre_required": False,
                "intake_terms": ["March", "August"],
                "application_deadline_fall": "January 15",
                "specializations": ["AI", "HCI", "Cybersecurity"],
            },
            {
                "name": "Master of Data Science",
                "degree_level": "Masters",
                "department": "School of CS",
                "duration_months": 18,
                "tuition_per_year_usd": 36500,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 85,
                "gre_required": False,
                "intake_terms": ["March", "August"],
                "application_deadline_fall": "January 15",
                "specializations": ["ML", "Big Data"],
            },
        ],
    },
    {
        "name": "Australian National University",
        "country": "Australia",
        "city": "Canberra, ACT",
        "qs_ranking": 34,
        "the_ranking": 67,
        "official_website": "https://www.anu.edu.au",
        "is_public": True,
        "description": "Australia's national university with strong research",
        "programs": [
            {
                "name": "Master of Computing",
                "degree_level": "Masters",
                "department": "CECS",
                "duration_months": 24,
                "tuition_per_year_usd": 33600,
                "min_gpa": 3.0,
                "ielts_min": 6.5,
                "toefl_min": 80,
                "gre_required": False,
                "intake_terms": ["February", "July"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI", "Systems", "HCI"],
            },
        ],
    },
    {
        "name": "University of Queensland",
        "country": "Australia",
        "city": "Brisbane, QLD",
        "qs_ranking": 43,
        "the_ranking": 70,
        "official_website": "https://www.uq.edu.au",
        "is_public": True,
        "description": "Queensland's leading research university",
        "programs": [
            {
                "name": "Master of Computer Science",
                "degree_level": "Masters",
                "department": "EECS",
                "duration_months": 24,
                "tuition_per_year_usd": 32850,
                "min_gpa": 2.7,
                "ielts_min": 6.5,
                "toefl_min": 87,
                "gre_required": False,
                "intake_terms": ["February", "July"],
                "application_deadline_fall": "November 30",
                "specializations": ["AI", "Data", "Security"],
            },
        ],
    },
    {
        "name": "UNSW Sydney",
        "country": "Australia",
        "city": "Sydney, NSW",
        "qs_ranking": 19,
        "the_ranking": 84,
        "official_website": "https://www.unsw.edu.au",
        "is_public": True,
        "description": "Strong engineering and tech-focused university",
        "programs": [
            {
                "name": "Master of Computer Science",
                "degree_level": "Masters",
                "department": "CSE",
                "duration_months": 24,
                "tuition_per_year_usd": 33600,
                "min_gpa": 2.7,
                "ielts_min": 6.5,
                "toefl_min": 90,
                "gre_required": False,
                "intake_terms": ["February", "May", "September"],
                "application_deadline_fall": "November 30",
                "specializations": ["AI", "DB", "Security"],
            },
        ],
    },
    {
        "name": "Monash University",
        "country": "Australia",
        "city": "Melbourne, VIC",
        "qs_ranking": 42,
        "the_ranking": 54,
        "official_website": "https://www.monash.edu",
        "is_public": True,
        "description": "Australia's largest university with global campuses",
        "programs": [
            {
                "name": "Master of Artificial Intelligence",
                "degree_level": "Masters",
                "department": "IT",
                "duration_months": 24,
                "tuition_per_year_usd": 33700,
                "min_gpa": 2.7,
                "ielts_min": 6.5,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["February", "July"],
                "application_deadline_fall": "Rolling",
                "specializations": ["AI", "ML", "Data Science"],
            },
            {
                "name": "Master of Data Science",
                "degree_level": "Masters",
                "department": "IT",
                "duration_months": 24,
                "tuition_per_year_usd": 33700,
                "min_gpa": 2.7,
                "ielts_min": 6.5,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["February", "July"],
                "application_deadline_fall": "Rolling",
                "specializations": ["ML", "Big Data", "Analytics"],
            },
        ],
    },
    {
        "name": "University of Adelaide",
        "country": "Australia",
        "city": "Adelaide, SA",
        "qs_ranking": 89,
        "the_ranking": 111,
        "official_website": "https://www.adelaide.edu.au",
        "is_public": True,
        "description": "Group of Eight university with affordable living costs",
        "programs": [
            {
                "name": "Master of Computer Science",
                "degree_level": "Masters",
                "department": "School of CS",
                "duration_months": 24,
                "tuition_per_year_usd": 31500,
                "min_gpa": 2.7,
                "ielts_min": 6.0,
                "toefl_min": 79,
                "gre_required": False,
                "intake_terms": ["February", "July"],
                "application_deadline_fall": "December 1",
                "specializations": ["AI", "Networks", "Software"],
            },
        ],
    },
    {
        "name": "University of Western Australia",
        "country": "Australia",
        "city": "Perth, WA",
        "qs_ranking": 72,
        "the_ranking": 125,
        "official_website": "https://www.uwa.edu.au",
        "is_public": True,
        "description": "Group of Eight university on Australia's west coast",
        "programs": [
            {
                "name": "Master of Information Technology",
                "degree_level": "Masters",
                "department": "CSSE",
                "duration_months": 24,
                "tuition_per_year_usd": 30500,
                "min_gpa": 2.7,
                "ielts_min": 6.5,
                "toefl_min": 82,
                "gre_required": False,
                "intake_terms": ["February", "July"],
                "application_deadline_fall": "December 15",
                "specializations": ["AI", "Data Science", "Software"],
            },
        ],
    },
]
