from fpdf import FPDF
from models import User, University, UserProfile
import io
from datetime import datetime

class PDF(FPDF):
    def header(self):
        # Header Line
        self.set_draw_color(37, 99, 235) # Blue-600
        self.set_line_width(0.5)
        self.line(10, 25, 200, 25)
        
        # AI Counsellor Branding
        self.set_font('helvetica', 'B', 12)
        self.set_text_color(37, 99, 235) 
        self.cell(0, 10, 'AI Counsellor', align='L')
        
        # Report Title in Header
        self.set_y(15)
        self.set_font('helvetica', 'I', 10)
        self.set_text_color(107, 114, 128) # Gray-500
        self.cell(0, 10, 'Admission Strategy Report', align='R')
        self.ln(20)

    def footer(self):
        self.set_y(-20)
        
        # Footer Line
        self.set_draw_color(229, 231, 235) # Gray-200
        self.set_line_width(0.2)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(156, 163, 175) # Gray-400
        self.cell(0, 5, 'Generated by AI Counsellor - Confidential', align='L')
        self.set_x(0)
        self.cell(0, 5, f'Page {self.page_no()}/{{nb}}', align='R')

class StrategyReportGenerator:
    def __init__(self, user: User, university: University, profile: UserProfile):
        self.user = user
        self.university = university
        self.profile = profile
        self.pdf = PDF()
        self.pdf.alias_nb_pages()
        self.pdf.add_page()
        self.pdf.set_auto_page_break(auto=True, margin=20)

    def generate(self) -> bytes:
        self._add_cover_page()
        self._add_profile_summary()
        self._add_university_analysis()
        self._add_action_plan()
        
        return bytes(self.pdf.output())

    def _add_cover_page(self):
        self.pdf.set_y(60)
        
        # University Name (Large)
        self.pdf.set_font('helvetica', 'B', 28)
        self.pdf.set_text_color(17, 24, 39) # Gray-900
        self.pdf.multi_cell(0, 15, self.university.name, align='C')
        self.pdf.ln(10)
        
        # Subtitle
        self.pdf.set_font('helvetica', '', 14)
        self.pdf.set_text_color(75, 85, 99) # Gray-600
        self.pdf.cell(0, 10, 'Personalized Admission Strategy Strategy', align='C', new_x="LMARGIN", new_y="NEXT")
        self.pdf.ln(20)
        
        # Prepared For Box
        self.pdf.set_fill_color(249, 250, 251) # Gray-50
        self.pdf.rect(60, 150, 90, 40, 'F')
        self.pdf.set_y(155)
        
        self.pdf.set_font('helvetica', 'B', 10)
        self.pdf.set_text_color(107, 114, 128)
        self.pdf.cell(0, 5, 'PREPARED FOR', align='C', new_x="LMARGIN", new_y="NEXT")
        
        self.pdf.set_font('helvetica', 'B', 14)
        self.pdf.set_text_color(17, 24, 39)
        self.pdf.cell(0, 10, self.user.full_name, align='C', new_x="LMARGIN", new_y="NEXT")
        
        self.pdf.set_font('helvetica', '', 10)
        self.pdf.set_text_color(107, 114, 128)
        self.pdf.cell(0, 5, datetime.now().strftime("%B %d, %Y"), align='C', new_x="LMARGIN", new_y="NEXT")

    def _add_section_header(self, title):
        self.pdf.ln(10)
        self.pdf.set_font('helvetica', 'B', 14)
        self.pdf.set_text_color(37, 99, 235) # Blue-600
        self.pdf.cell(0, 10, title.upper(), new_x="LMARGIN", new_y="NEXT")
        
        # Underline
        self.pdf.set_draw_color(229, 231, 235)
        self.pdf.line(self.pdf.get_x(), self.pdf.get_y(), 200, self.pdf.get_y())
        self.pdf.ln(5)

    def _add_profile_summary(self):
        self.pdf.add_page()
        self._add_section_header('Applicant Snapshot')
        
        self.pdf.set_font('helvetica', '', 11)
        self.pdf.set_text_color(55, 65, 81) # Gray-700
        
        data = [
            ("Degree Interest", self.profile.intended_degree),
            ("Field of Study", self.profile.field_of_study),
            ("Current GPA", f"{self.profile.gpa}/4.0" if self.profile.gpa else "N/A"),
            ("Budget", f"${self.profile.budget_per_year:,}/yr" if self.profile.budget_per_year else "N/A"),
        ]
        
        # Grid layout
        for i in range(0, len(data), 2):
            self.pdf.ln(2)
            # Col 1
            key1, val1 = data[i]
            self.pdf.set_x(15)
            self.pdf.set_font('helvetica', 'B', 10)
            self.pdf.set_text_color(107, 114, 128)
            self.pdf.cell(40, 6, key1)
            self.pdf.set_font('helvetica', '', 11)
            self.pdf.set_text_color(17, 24, 39)
            self.pdf.cell(50, 6, str(val1))
            
            # Col 2
            if i + 1 < len(data):
                key2, val2 = data[i+1]
                self.pdf.set_font('helvetica', 'B', 10)
                self.pdf.set_text_color(107, 114, 128)
                self.pdf.cell(40, 6, key2)
                self.pdf.set_font('helvetica', '', 11)
                self.pdf.set_text_color(17, 24, 39)
                self.pdf.cell(50, 6, str(val2))
            
            self.pdf.ln(8)
            
        self.pdf.ln(5)

    def _add_university_analysis(self):
        self._add_section_header('University Analysis')
        
        # University Header Box
        self.pdf.set_fill_color(243, 244, 246) # Gray-100
        self.pdf.rect(10, self.pdf.get_y(), 190, 20, 'F')
        
        self.pdf.set_y(self.pdf.get_y() + 5)
        self.pdf.set_x(15)
        self.pdf.set_font('helvetica', 'B', 12)
        self.pdf.set_text_color(17, 24, 39)
        rank_text = f"Global Rank: #{self.university.qs_ranking}" if self.university.qs_ranking else "Ranking: N/A"
        self.pdf.cell(90, 10, rank_text)
        
        self.pdf.set_x(110)
        loc_text = f"Location: {self.university.city}, {self.university.country}" if self.university.city else f"Location: {self.university.country}"
        self.pdf.cell(90, 10, loc_text, align='R')
        self.pdf.ln(20)
        
        # Analysis Text
        self.pdf.set_font('helvetica', '', 11)
        self.pdf.set_text_color(55, 65, 81)
        
        fit_paragraph = (
            f"As a {self.university.country}-based institution, {self.university.name} is a strategic choice for students "
            f"targeting {self.profile.field_of_study}. Your GPA of {self.profile.gpa} places you in a competitive position. "
            "However, admission committees at this level heavily weigh the narrative of your Statement of Purpose (SOP) "
            "and alignment with faculty research."
        )
        
        self.pdf.set_x(15)
        self.pdf.multi_cell(0, 6, fit_paragraph)
        self.pdf.ln(5)

    def _add_action_plan(self):
        self._add_section_header('Strategic Action Plan')
        
        actions = [
            ("SOP Customization", "Mention specific professors and labs. Your goal is to show 'fit', not just merit."),
            ("Timeline Management", "Submit your application at least 2 weeks before the deadline to avoid technical issues."),
            ("Networking", "Connect with 2-3 current students or alumni on LinkedIn to understand the campus culture."),
            ("Document Verification", "Ensure all transcripts are WES verified if required by the university.")
        ]
        
        for title, desc in actions:
            self.pdf.set_x(15)
            # Checkbox icon
            self.pdf.set_font('courier', 'B', 14)
            self.pdf.set_text_color(37, 99, 235)
            self.pdf.cell(10, 8, "[ ]", align='C')
            
            # Title
            self.pdf.set_font('helvetica', 'B', 11)
            self.pdf.set_text_color(17, 24, 39)
            self.pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
            
            # Description
            self.pdf.set_x(25)
            self.pdf.set_font('helvetica', '', 10)
            self.pdf.set_text_color(75, 85, 99)
            self.pdf.multi_cell(0, 5, desc)
            self.pdf.ln(4)
